INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'001', N'', N'Tài sản thuê ngoài', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'002', N'', N'Vật tư, h/hoá giữ hộ,gia công', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'003', N'', N'Hàng hoá nhận bán hộ , ký gửi', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'004', N'', N'Nợ khó đòi đã xử lý', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'007', N'', N'Ngoại tệ các loại', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'008', N'', N'Dự toán chi sự nghiệp,dự án', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'111', N'', N'Tiền mặt', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1111', N'', N'Tiền mặt tại quỹ', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'11111', N'', N'Tiền mặt tại quỹ 1', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'11112', N'', N'Tiền mặt tại quỹ 2', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'11113', N'', N'Tiền mặt tại quỹ 3', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1112', N'', N'Ngoại tệ', NULL, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1113', N'', N'Vàng SJC', 1, N'')

INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'129', N'', N'Dự phòng giảm giá Đ/tư ngắn ha', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'131', N'', N'Phải thu khách hàng', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1311', N'', N'Xuất bán', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1312', N'', N'Xuất bán khách lẻ', 1, N'')

INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1314', N'', N'Phải thu khách hàng - Phân ĐC', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1317', NULL, N'Phải thu khách hàng- dài hạn', 1, NULL)
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1318', N'', N'Phải thu khác khách hàng-Kho..', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'133', N'', N'Thuế GTGT được khấu trừ', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1331', N'', N'Thuế GTGT hhóa  dvụ được ktrừ', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1332', N'', N'Thuế GTGT TSCĐ được khấu trừ', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1333', N'', N'Thuế GTGT đề nghị hoàn', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'136', N'', N'Phải thu nội bộ', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'138', N'', N'Phải thu khác', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1381', N'', N'Tài sản thiếu chờ xử lý', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1382', N'', N'Phải thu phí NH', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1383', N'', N'Phải thu lãi cho vay', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1385', N'', N'Phải thu về cổ phần ho', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1387', N'', N'Phải thu thuế TNCN', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1388', N'', N'Phải thu khác', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'139', N'', N'Dự phòng phải thu khó đòi', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'141', N'', N'Tạm ứng', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'142', N'', N'Chi phí trả trước ngắn hạn', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1421', N'', N'CP trả trước NH-ĐKý lưu hành..', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1422', N'', N'CP trả trước NH-Công cụ dg cụ', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'144', N'', N'Thế chấp,ký quỹ,ký cược ngắn h', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'151', N'', N'Hàng mua đang đi trên đường', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'152', N'', N'Nguyên liệu, vật liệu', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1521', N'', N'Nguyên liệu, vật liệu chính', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1522', N'', N'Nguyên liệu, vật liệu phụ', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1523', N'', N'Nhiên liệu', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'153', N'', N'Công cụ, dụng cụ', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1531', N'', N'Công cụ, dụng cụ', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1532', N'', N'Bao bì luân chuyển', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1533', N'', N'Vật dụng đóng gói', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1534', N'', N'Phụ tùng thay thế', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'154', N'', N'Chi phí sản xuất,k.d dở dang', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'155', N'', N'Thành phẩm', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1551', N'', N'Thành phẩm-thuốc BVTV', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1552', N'', N'Thành phẩm-phân', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1553', N'', N'Thành phẩm-phân ĐC', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1554', N'', N'Thành phẩm-gia công', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'156', N'', N'Hàng hóa', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1561', N'', N'Hhóa thành phẩm', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'15611', N'', N'Hhóa -Thuốc BVTV', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'15612', N'', N'HH NK-Thuốc BVTV', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'15613', N'', N'Hhóa - Phân bón', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'15614', N'', N'Hhóa - Phân ĐC', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'15615', N'', N'Hhóa-Máy móc, thiết bị', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'15618', N'', N'Hhoá vật phẩm biếu tặng,kmãi..', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1562', N'', N'CP thu mua, nhận hàng...', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'1567', N'', N'H.hoá bất động sản', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'157', N'', N'Hàng gởi đi bán', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'158', N'', N'Hàng hoá kho bảo thuế', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'159', N'', N'Dự phòng giảm giá hàng tồn kho', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'161', N'', N'', NULL, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'171', N'', N'', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'229', N'', N'Dự phòng giảm giá Đ/tư dài hạn', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'22931', NULL, N'Dự phòng phải thu khó đòi - Ngắn hạn', 1, NULL)
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'22932', NULL, N'Dự phòng phải thu khó đòi - Dài hạn', 1, NULL)
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'2294', N'', N'', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'2413', N'', N'Sữa chữa lớn TSCĐ dở dang', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'243', N'', N'Tàisản thuế thu nhập hoãn lại', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'311', N'', N'Vay ngắn hạn các đối tượng', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3111', N'', N'Vay ngắn hạn - VND', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'31111', N'', N'Vay ngắn hạn ngân hàng', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'31112', N'', N'Vay ngắn hạn đại lý', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'31113', N'', N'Vay ngắn hạn cá nhân', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'315', N'', N'Nợ dài hạn đến hạn trả', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'331', N'', N'Phải trả cho người cung cấp', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3311', N'', N'P.trả người ccấp (BVTV+NLiệu)', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3312', N'', N'P.trả người cấp (V/chuyển)', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3313', N'', N'P.trả người cấp (Phân bón)', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3314', N'', N'P.trả nguời c.cấp TSCD', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3315', N'', N'Lãi do thanh toán trễ hạn ĐL', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3316', N'', N'P.trả nhập khẩu (BVTV+NLiệu)', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3317', N'', N'P.trả  nhập máy móc, thiết bị', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3318', N'', N'Phải trả các nhà cung cấp-Khác', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'33181', NULL, N'Phải trả các nhà cung cấp- Khác -ngắn hạn', 1, NULL)
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'33182', NULL, N'Phải trả các nhà cung cấp- Khác- dài hạn', 1, NULL)
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'333', N'', N'Thuế và các khoản phải nộp NN', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3331', N'', N'Thuế GTGT phải nộp', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'33311', N'', N'Thuế GTGT đầu ra', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'33312', N'', N'Thuế GTGT hàng nhập khẩu', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3332', N'', N'Thuế tiêu thụ đặc biệt', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3333', N'', N'Thuế xuất nhập khẩu', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'33331', N'', N'Thuế xuất khẩu', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'33332', N'', N'Thuế nhập khẩu', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3334', N'', N'Thuế thu nhập doanh nghiệp', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3335', N'', N'Thuế thu nhập cá nhân', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'33351', N'', N'Thuế TNCN tiền lương, t. công', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'33352', N'', N'Thuế TNCN đầu tư vốn', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'33353', NULL, N'Thuế TNCN từ trúng thưởng', 1, NULL)
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3336', N'', N'Thuế tài nguyên', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3337', N'', N'Thuế nhà đất, tiền thuê đất', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3338', N'', N'Các loại thuế khác', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'33381', N'', N'Thuế thu nhập cá nhân(bỏ)', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'33382', N'', N'Các loại thuế khác', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'33383', N'', N'Thuế trước bạ', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'33385', N'', N'Thuế môn bài', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3339', N'', N'Phí ,lệ phí và các khoản phải nộp khác', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'334', N'', N'Phải trả công nhân viên', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3341', N'', N'Phải trả  CBCNV- lương', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3342', N'', N'Phải trả CBCNV - ngoài giờ', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3343', N'', N'Phải trả CBCNV - Lương thg 13', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3344', N'', N'Trợ cấp nghỉ hưu và thôi việc', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3345', N'', N'Phải trả CBCNV - ăn ca', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3348', N'', N'Phải trả người lao động khác', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'335', N'', N'Chi phí phải trả', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3351', N'', N'CP phải trả-lãi vay cá nhân', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3352', N'', N'Chi phí phải trả-thuê đất,nhà.', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3353', N'', N'Chi phí trả trước-giá thành gc', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3354', N'', N'Chi phí trả trước-gthành bao b', 1, N'')
GO
print 'Processed 300 total records'
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3355', N'', N'Chi phí trả trước-gthành,NgL', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3356', N'', N'Chi phí trả trước - phí CK', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3357', N'', N'Trích trước lương T13', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3358', N'', N'CP phải trả -lãi vay ngân hàng', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3359', N'', N'CP Phải trả trước-khác', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'336', N'', N'Phải trả nội bộ', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'338', N'', N'Phải trả, phải nộp khác', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3381', N'', N'Tài sản thừa chờ xử lý', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3382', N'', N'Kinh phí công đoàn', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3383', N'', N'Bảo hiểm xã hội', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3384', N'', N'Bảo hiểm y tế', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3385', N'', N'Phải trả về cổ phần ho', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3386', N'', N'Nhận ký quỹ,ký cược ngắn hạn', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3387', N'', N'Doanh thu chưa thực hiện', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'33871', N'', N'', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'33872', N'', N'', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3388', N'', N'Phải trả, phải nộp khác', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'33881', N'', N'Phải trả phải nộp-phạt TT ĐLý', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'33882', N'', N'Phải trả , phải nộp khác', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'338821', N'', N'', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'338822', N'', N'', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'33883', N'', N'Phải trả thuế TNCN', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'33884', NULL, N'Đoàn phí công đoàn', 1, NULL)
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3389', N'', N'Bảo hiểm thất nghiệp', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'341', N'', N'Vay dài hạn', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3411', N'', N'Vay dài hạn VND', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'34111', N'', N'Vay dài hạn ngân hàng', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'341111', N'', N'', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'341112', N'', N'', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'34113', N'', N'Vay dài hạn cá nhân', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3412', N'', N'', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'342', N'', N'Nợ dài hạn', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'343', N'', N'Trái phiếu phát hành', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3431', N'', N'Mệnh giá trái phiếu', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'34311', N'', N'', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'343111', N'', N'', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'343112', N'', N'', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'34312', N'', N'', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'34313', N'', N'', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3432', N'', N'Chiết khấu trái phiếu', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3433', N'', N'Phụ trội trái phiếu', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'344', N'', N'Nhận ký cược, ký quỹ dài hạn', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3441', N'', N'Nhận ký cược, ký quỹ dài hạn', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3442', N'', N'Nhận ký cược, ký quỹ dài hạn', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'347', N'', N'Thuế T.nhập hoãn lại phải trả', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'351', N'', N'Quỹ dự phòng trợ cấp mất việc', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'352', N'', N'Dự phòng phải trả', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3521', N'', N'', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3522', N'', N'', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3523', N'', N'', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3524', N'', N'', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'353', N'', N'Quỹ khen thưởng , phúc lợi', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3531', N'', N'Quỹ khen thưởng', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3532', N'', N'Quỹ phúc  lợi', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3533', N'', N'', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3534', N'', N'', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'356', N'', N'', NULL, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3561', N'', N'', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'3562', N'', N'', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'357', N'', N'', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'411', N'', N'Nguồn vốn kinh doanh', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'4111', N'', N'Vốn đầu tư chủ sở hữu', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'41111', N'', N'', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'41112', N'', N'', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'4112', N'', N'Thặng dư vốn cổ phần', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'4113', N'', N'', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'4118', N'', N'Vốn khác', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'412', N'', N'Chênh lệch đánh giá lại TS', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'413', N'', N'Chênh lệch tỷ gi', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'4131', N'', N'CL tỷ giá đánh giá cuối năm TC', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'4132', N'', N'CL tỷ giá giai đoạn Đ.tư XDCB', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'414', N'', N'Quỹ đầu tư phát triển', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'415', N'', N'Quỹ dự phòng TC', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'417', N'', N'', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'418', N'', N'Quỹ khác thuộc vốn chủ SH', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'419', N'', N'Cổ phiếu quỹ', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'421', N'', N'Lợi nhuận chưa phân phối', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'4211', N'', N'L.nhuận chưa phối năm trước', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'4212', N'', N'L.nhuận chưa phối năm nay', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'431', N'', N'Quỹ khen thưởng, phúc lợi', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'4311', N'', N'Quỹ khen thưởng', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'4312', N'', N'Quỹ phúc lợi', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'4313', N'', N'Quỹ  ph.lợi đã hình thành TSCĐ', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'441', N'', N'', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'461', N'', N'', NULL, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'466', N'', N'', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'511', N'', N'Doanh thu bán hàng', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'5111', N'', N'Doanh thu bán h.ho', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'51111', N'', N'DT bán h.hoá-Thuốc BVTV', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'51112', N'', N'DT bán h.hoá-Phân bón', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'51113', N'', N'DT bán h.hoá-Phân ĐC', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'5112', N'', N'DT bán thành phẩm', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'51121', N'', N'DT t.phẩm-Sx-G.công BVTV', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'51122', N'', N'DT thành phẩm-phân', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'5113', N'', N'Doanh thu cung cấp dịch vụ', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'51131', N'', N'DT cung cấp DV-thuê kho,b.xếp', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'51132', N'', N'DT cung cấp DV-khác', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'5114', N'', N'Doanh thu trợ cấp,trợ gi', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'5117', N'', N'Doanh thu bất động sản', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'5118', N'', N'Doanh thu bán hàng khác', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'512', N'', N'Doanh thu bán hàng nội bộ', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'5121', N'', N'DT hàng hoá nội bộ', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'51211', N'', N'DT h.hoá nội bộ-thuốc', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'51212', N'', N'DT h.hoá nội bộ-phân', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'51213', N'', N'DT h.hoá nội bộ-phân ĐC', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'5122', N'', N'DT thành phẩm-SX nội bộ', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'51221', N'', N'DT T.phẩm,Sx,Gc nội bộ', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'51222', N'', N'DT T.phẩm nội bộ-phân', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'5123', N'', N'DT cc dịch vụ nội bộ', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'51231', N'', N'DT dịch vụ nội bộ-thuê kho...', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'51232', N'', N'DT dịch vụ nội bộ khác', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'5128', N'', N'DT bán hàng nội bộ khác', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'515', N'', N'Doanh thu hoạt động tài chính', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'5151', N'', N'D.thu TGNH, trái phiếu ..', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'5152', N'', N'D thu do t toán trễ hạn ĐL', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'5153', N'', N'D.thu CKhấu từ nhà cung cấp.', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'5154', N'', N'D.thu C.nhượng, cho thuê CSHT', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'5155', N'', N'D.thu lãi C.lệch tgiá ng. tệ', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'5156', N'', N'D.thu hoạt động tài chính khác', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'5158', N'', N'D.thu các hđộng đầu tư khác', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'521', N'', N'Các khoản giảm trừ doanh thu', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'5211', N'', N'Chiết khấu TM', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'52111', N'', N'Chiết khấu TM', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'52112', N'', N'Chiết khấu TM', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'5212', N'', N'Hàng bán bị trả lại ', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'52121', NULL, N'Hàng bán bị trả lại', 1, NULL)
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'52122', NULL, N'Hàng bán bị trả lại', 1, NULL)
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'5213', N'', N'Giảm giá hàng bán ', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'52131', NULL, N'Giảm giá hàng bán', 1, NULL)
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'52132', NULL, N'Giảm giá hàng bán', 1, NULL)
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'531', N'', N'Hàng bán bị trả lại', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'5311', N'', N'Hàng bán bị trả lại-Thuốc BVTV', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'5313', N'', N'Hàng bán bị trả lại-Phân bón', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'532', N'', N'Giảm giá hàng bán', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'5321', N'', N'Giảm giá hàng bán-Thuốc', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'5323', N'', N'Giảm giá hàng bán-Phân', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'621', N'', N'CP ng-liệu,vật liệu trực tiếp', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6211', N'', N'CP ng.liệu chính trực tiếp', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6212', N'', N'CP V.liệu phụ, b.bì trực tiếp', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'622', N'', N'CP nhân công trực tiếp', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'62212', N'', N'CP PLBB công nhân TTSX', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'62213', N'', N'CP PL không BB CNSX', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'627', N'', N'CP sản xuất chung', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6271', N'', N'CP nhân viên phân xưởng(SX)', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'62711', N'', N'CP lương QLPX', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'62712', N'', N'CP lương tháng13 QLPX', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'62713', N'', N'CP PLBB QLPX(BHXH,BHYT,...', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'62714', N'', N'CP PL không BB QLPX', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6272', N'', N'CP vật liệu(bảo dưỡng TSCĐ,..)', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6273', N'', N'CP dụng cụ sản xuất', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6274', N'', N'CP kh.hao TSCĐ dùng SX', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6277', N'', N'CP d/v mua ngoài (SX)', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'62771', N'', N'CP thuê đất, bảo dưỡng hạ tầng', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'62772', N'', N'CP xử lí chất thải', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'62773', N'', N'CP điện phục vụ SX', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'62774', N'', N'CP nước phục vụ SX', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'62775', N'', N'CP điện thoại phục vụ SX', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'62777', N'', N'CP tiền ăn giữa ca CNSX', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'62778', N'', N'CP DV SX mua ngoài khác', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6278', N'', N'CP bằng tiền khác (sản xuất)', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'632', N'', N'Giá vốn hàng bán', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6321', N'', N'Giá vốn hàng ho', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'63211', N'', N'Giá vốn hàng hoá-Thuốc BVTV', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'63212', N'', N'Giá vốn h.hoá-Phân bón', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'63213', N'', N'Giá vốn h.hoá-Phân ĐC', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6322', N'', N'Giá vốn thành phẩm', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'63221', N'', N'Giá vốn t.phẩm-Sx-G.công BVTV', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'63222', N'', N'Giá vốn thành phẩm-Thuốc BVTV', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6323', N'', N'Giá vốn dịch vụ', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'63231', N'', N'Giá vốn DV-thuê kho,b.xếp', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'63232', N'', N'Giá vốn DV-khác', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6324', N'', N'Giá vốn vượt ĐM sản xuất', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'63241', N'', N'Giá vốn vượt ĐM sản xuất NL', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'63242', N'', N'Giá vốn vượt ĐM sản xuất B.B', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'63243', NULL, N'Giá vốn vượt ĐM TP tái chế', 1, NULL)
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6325', NULL, N'Giá vốn thành phẩm dùng để khuyến mại (Không đăng kí)', 1, NULL)
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6328', N'', N'Giá vốn hàng bán khác', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'635', N'', N'Chi phí tài chính', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6351', N'', N'Chi phí trả lãi tiền vay', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6352', N'', N'CP lãi do thanh toán trước hạn', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6353', N'', N'Chi phí phạt t.toán-Nhà PPhối', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6354', N'', N'Phí nhận hạn mức tín dụng', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6355', N'', N'Chi phí ch.chênh lệch tỉ gi', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6356', N'', N'Chi phí trả lãi vay vượt mức', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6357', N'', N'Chi phí thuê bảo vệ hàng TChấp', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6358', N'', N'Chi phí tài chính khác', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'641', N'', N'Chi phí bán hàng', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6411', N'', N'Chi phí nhân viên(bán hàng)', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64111', N'', N'CP lương NV bán hàng', 1, N'')
GO
print 'Processed 500 total records'
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64112', N'', N'CP lương tháng 13 NV bán hàng', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64113', N'', N'CP PLBB NVBH(BHXH,BHYT,..', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64114', N'', N'CP PL không BB NV bán hàng', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6412', N'', N'Chi phí nhiên liệu, sửa xe', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64121', N'', N'Chi phí nhiên liệu, nhớt', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64122', N'', N'Chi phí sửa xe, dầu mỡ, lọc..', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64123', N'', N'Chi phí rửa xe, vệ sinh xe', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64124', N'', N'Phí kiểm định xe', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6413', N'', N'Chi phí v/chuyển hàng bán', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64131', N'', N'Chi phí v/chuyển hàng bán-BVTV', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64132', N'', N'Chi phí v/chuyển hàng bán-Phân', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64138', N'', N'Chi phí v/chuyển hàng bán-khác', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6414', N'', N'', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6415', N'', N'CP bbì, t.kế nhãn, đký sử dụng', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64151', N'', N'C.phí thiết bị,bao bì, nhãn...', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64152', N'', N'C.phí đăng ký sử dụng, lưu hàn', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6417', N'', N'Chi phí quảng bá, hội thảo...', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64171', N'', N'CP q.cáo, tiếp thị, k.mãi', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'641711', N'', N'Chi phí quảng bá sản phẩm', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'641712', N'', N'Chi phí tiếp thị, khuyến mãi', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64172', N'', N'CP hội nghị khách hàng,cổ đông', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64173', N'', N'CP tnghiệm, trình diễn,hthảođb', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64175', NULL, N'Chi phí bảo hiểm TN NLĐ', 1, NULL)
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64178', N'', N'C.phí thuê ngoài khác: CTV...', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6418', N'', N'Chi phí bán hàng khác', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64181', N'', N'CP NVKD tiếp khách', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64182', N'', N'CP khách sạn, lưu trú, nhà trọ', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64183', N'', N'Phí vật dụng , VPP bán hàng', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64184', N'', N'CP vé mbay, tàu, taxi, xe ctác', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64185', N'', N'CP phà, cầu đường, lệ phí gt', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64186', N'', N'Chi phí bưu phẩm, bưu điện...', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64187', N'', N'Phí bảo hiểm vận chuyển H.Ho', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64188', N'', N'Chi phí linh tinh khác', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64189', N'', N'Chi phí bán hàng chưa hợp lệ', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'642', N'', N'CP quản lý doanh nghiệp', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6421', N'', N'CP quản lý nhân viên', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64211', N'', N'CP lương QLNV', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64212', N'', N'CP lương tháng 13 QLNV', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64213', N'', N'CP PLBB QLNV(BHXH,BHYT,...', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64214', N'', N'CP PL không BB QLNV', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6422', N'', N'CP vật liệu quản lý', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6423', N'', N'Chi phí đồ dùng Văn phòng', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64231', N'', N'Chi phí văn phòng phẩm', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64232', N'', N'Chi phí bảo hộ lao động', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64233', N'', N'Chi phí công cụ,dụng cụ ...', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64234', N'', N'Chi phí sữa chữa , thay thế dc', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'64238', N'', N'Chi phí đồ dùng khác', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6424', N'', N'CP khấu hao TSCĐ', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'6425', N'', N'Thuế, phí và lệ phí', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'711', N'', N'Thu nhập khác', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'811', N'', N'Chi phí khác', 0, N'')

INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'821', N'', N'Chi phí thuế TNDN', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'8211', N'', N'Chi phí thuế TNDN hiện hành', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'8212', N'', N'Chi phí thuế TNDN hoãn lại', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'911', N'', N'Xác định kết quả kinh doanh', 0, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'9111', N'', N'Xác định KQKD-h.ho', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'9112', N'', N'Xác định KQKD tphẩm(sx/gc)', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'9113', N'', N'Xác định KQKD dịch vụ', 1, N'')
INSERT [dbo].[DM_TAIKHOAN] ([Matk], [Manhom], [Taikhoan], [Tietkhoan], [Candoi]) VALUES (N'9118', N'', N'Xác định KQKD khác', 1, N'')

INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'014A7705-A9A4-44A5-831E-3158CEE36CD7', NULL, N'mnuHH', N'Hàng Hóa', NULL, N'HH', NULL, NULL, N'0', NULL, NULL, NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'03C46C08-3496-4895-9F2E-A51EEE8CBCC0', NULL, N'mnuDM', N'Quản lý danh mục', NULL, N'DM', NULL, NULL, N'0', NULL, N'', NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'03C46C08-3496-4895-9F2E-A51EEE8CBCC1', N'03C46C08-3496-4895-9F2E-A51EEE8CBCC0', N'mnuDM_KHO', N'Danh mục kho', NULL, N'DM', NULL, NULL, N'1', NULL, N'', NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'03C46C08-3496-4895-9F2E-A51EEE8CBCC2', N'71135D27-1DDC-4E5A-B402-90B9A75161AF', N'mnuBC_THEKHO', N'Thẻ Kho', NULL, N'BC', NULL, NULL, N'1', NULL, N'', NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'03C46C08-3496-4895-9F2E-A51EEE8CBCC3', N'014A7705-A9A4-44A5-831E-3158CEE36CD7', N'mnuHH_PHIEUXUAT', N'Phiếu Xuất', NULL, N'PX', NULL, NULL, N'1', NULL, N'', NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'03C46C08-3496-4895-9F2E-A51EEE8CBCC4', N'014A7705-A9A4-44A5-831E-3158CEE36CD7', N'mnuHH_PHIEUNHAP', N'Phiếu Nhập', NULL, N'PN', NULL, NULL, N'1', NULL, N'', NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'03C46C08-3496-4895-9F2E-A51EEE8CBCC5', N'03C46C08-3496-4895-9F2E-A51EEE8CBCC0', N'mnuDM_SANPHAM', N'Danh mục sản phẩm', NULL, N'DM', NULL, NULL, N'1', NULL, N'', NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'03C46C08-3496-4895-9F2E-A51EEE8CBCC6', N'03C46C08-3496-4895-9F2E-A51EEE8CBCC0', N'mnuDM_NHOMSANPHAM', N'Danh mục nhóm sản phẩm', NULL, N'DM', NULL, NULL, N'1', NULL, N'', NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'03C46C08-3496-4895-9F2E-A51EEE8CBCC7', N'03C46C08-3496-4895-9F2E-A51EEE8CBCC0', N'mnuDM_XE', N'Danh mục Xe', NULL, N'DM', NULL, NULL, N'1', NULL, N'', NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'03C46C08-3496-4895-9F2E-A51EEE8CBCC8', N'03C46C08-3496-4895-9F2E-A51EEE8CBCC0', N'mnuDM_DONGIA', N'Đơn giá xuất', NULL, N'DM', NULL, NULL, N'1', NULL, N'', NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'03C46C08-3496-4895-9F2E-A51EEE8CBCC9', N'014A7705-A9A4-44A5-831E-3158CEE36CD7', N'mnuHH_CHANHXE', N'Chành xe', NULL, N'CX', NULL, NULL, N'1', NULL, N'', NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'03C46C08-3496-4895-9F2E-A51EEE8CBCF1', N'03C46C08-3496-4895-9F2E-A51EEE8CBCC0', N'mnuDM_KHACHHANG', N'Khách hàng', NULL, N'DM', NULL, NULL, N'1', NULL, NULL, NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'03C46C08-3496-4895-9F2E-A51EEE8CBCF2', N'03C46C08-3496-4895-9F2E-A51EEE8CBCC0', N'mnuDM_CHIPHI', N'Chi phí', NULL, N'DM', NULL, NULL, N'1', NULL, NULL, NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'03C46C08-3496-4895-9F2E-A51EEE8CBCF3', N'03C46C08-3496-4895-9F2E-A51EEE8CBCC0', N'mnuDM_TAIKHOAN', N'Tài khoản', NULL, N'DM', NULL, NULL, N'1', NULL, NULL, NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'03C46C08-3496-4895-9F2E-A51EEE8CBCF4', N'03C46C08-3496-4895-9F2E-A51EEE8CBCC0', N'mnuDM_NHANVIEN', N'Nhân viên', NULL, N'DM', NULL, NULL, N'1', NULL, NULL, NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'03F8CD09-B558-413F-8937-9BC31F551C8D', N'03C46C08-3496-4895-9F2E-A51EEE8CBCC0', N'mnuDM_LYDO', N'Danh mục Lý do', NULL, N'DM', NULL, NULL, N'1', NULL, NULL, NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'0F053CB7-6A35-4106-BD3E-3636D9203A2B', NULL, N'mnuHT_THAMSO', N'Khai báo hệ thống', NULL, N'HT', NULL, NULL, N'1', NULL, NULL, NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'3887199A-D12F-45D7-9C25-5462EFAECFEF', NULL, N'mnuHT_PHUCHOI', N'Phục Hồi Dữ Liệu', NULL, N'HT', NULL, NULL, N'1', NULL, N'4', NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'3FCA4675-5B3B-4A1C-8C29-C4695DF2896F', NULL, N'mnuHT_QUYENHAN', N'Quyền Hạn', NULL, N'HT', NULL, NULL, N'1', NULL, N'2', NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'54B18EDC-F3B8-4467-A601-BCAFB478637D', NULL, N'mnuHT_SAOLUU', N'Sao Lưu Dữ Liệu', NULL, N'HT', NULL, NULL, N'1', NULL, N'3', NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'662651E2-E8D3-456A-BEF0-66B60CBAB098', NULL, N'mnuHT_THONGTIN', N'Thông Tin Chung', NULL, N'HT', NULL, NULL, N'1', NULL, N'5', NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'69CD8E3E-2D5D-4587-953D-EB1BCB346927', NULL, N'mnuHT_NGUOIDUNG', N'Người Dùng', NULL, N'HT', NULL, NULL, N'1', NULL, N'1', NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'71135D27-1DDC-4E5A-B402-90B9A75161AF', NULL, N'mnuBC', N'Báo cáo - Thống Kê', NULL, N'BC', NULL, NULL, N'0', NULL, NULL, NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'71135D27-1DDC-4E5A-B402-90B9A75161BH', N'71135D27-1DDC-4E5A-B402-90B9A75161AF', N'mnuBC_BANHANG', N'Báo cáo bán hàng', NULL, N'BC', NULL, NULL, N'1', NULL, N'2', NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'71135D27-1DDC-4E5A-B402-90B9A75161SS', N'71135D27-1DDC-4E5A-B402-90B9A75161AF', N'mnuBC_TKGUICHANH', N'Thống kê gửi chành', NULL, N'BC', NULL, NULL, N'1', NULL, NULL, NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'71135D27-1DDC-4E5A-B402-90B9A75161ZZ', N'71135D27-1DDC-4E5A-B402-90B9A75161AF', N'mnuBC_NHAPXUATTON', N'Báo cáo nhập xuất tồn', NULL, N'BC', NULL, NULL, N'1', NULL, N'3', NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'7411F1C8-01CA-457F-84AB-B85D7D61E200', NULL, N'mnuBH', N'Bán Hàng', NULL, N'BH', NULL, NULL, N'0', NULL, N'0', NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'7411F1C8-01CA-457F-84AB-B85D7D61E219', NULL, N'mnuHT', N'Hệ Thống', NULL, N'HT', NULL, NULL, N'0', NULL, NULL, NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'7411F1C8-01CA-457F-84AB-B85D7D61E220', NULL, N'mnuBC_PHAITHU', N'Công nợ phải thu', NULL, N'BC', NULL, NULL, N'0', NULL, NULL, NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'7411F1C8-01CA-457F-84AB-B85D7D61E221', N'7411F1C8-01CA-457F-84AB-B85D7D61E220', N'mnuBC_CONGNOTHU', N'Công nợ phải thu - Chi tiết', NULL, N'BC', NULL, NULL, N'1', NULL, NULL, NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'7411F1C8-01CA-457F-84AB-B85D7D61E222', N'7411F1C8-01CA-457F-84AB-B85D7D61E220', N'mnuBC_CONGNOTHUTH', N'Công nợ phải thu - Tổng hợp', NULL, N'BC', NULL, NULL, N'1', NULL, NULL, NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'7411F1C8-01CA-457F-84AB-B85D7D61E223', N'7411F1C8-01CA-457F-84AB-B85D7D61E220', N'mnuBC_CONGNOTRA', N'Công nợ phải trả', NULL, N'BC', NULL, NULL, N'1', NULL, NULL, NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'7411F1C8-01CA-457F-84AB-B85D7D61E244', N'7411F1C8-01CA-457F-84AB-B85D7D61E219', N'mnuHT_KETCHUYENSODU', N'Kết chuyển số dư', NULL, N'HT', NULL, NULL, N'1', NULL, N'2', NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'7411F1C8-01CA-457F-84AB-B85D7D61E245', NULL, N'mnuTC', N'Phiếu Thu Chi', NULL, N'TC', NULL, NULL, N'0', NULL, NULL, NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'7411F1C8-01CA-457F-84AB-B85D7D61E246', N'7411F1C8-01CA-457F-84AB-B85D7D61E245', N'mnuTC_PHIEUTHU', N'Phiếu thu', NULL, N'TC', NULL, NULL, N'1', NULL, NULL, NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'7411F1C8-01CA-457F-84AB-B85D7D61E247', N'7411F1C8-01CA-457F-84AB-B85D7D61E245', N'mnuTC_PHIEUCHI', N'Phiếu chi', NULL, N'TC', NULL, NULL, N'1', NULL, NULL, NULL)
INSERT [dbo].[DM_CHUCNANG] ([macn], [macnroot], [kyhieu], [chucnang], [tenform], [loaicn], [thumb], [icon], [cap], [muccon], [stt], [khongapdung]) VALUES (N'7411F1C8-01CA-457F-84AB-B85D7D61E2EE', N'7411F1C8-01CA-457F-84AB-B85D7D61E219', N'mnuHT_EXIT', N'Thoát', NULL, N'HT', NULL, NULL, N'1', NULL, N'3', NULL)
